knee_orientation : ">>"
pantograph_leg : false
odom_scaler: 1.0
max_linear_velocity_x : 50
max_linear_velocity_y : 250
max_angular_velocity_z : 100
com_x_translation : -0.04
swing_height : 0.04
stance_depth : 0.01
stance_duration : 0.35
nominal_height : 0.3
