base: base_link
left_front:
  - FL_hip_1
  - FL_thigh_1
  - FL_calf_1
  - FL_foot_1

right_front:
  - FR_hip_1
  - FR_thigh_2
  - FR_calf_2
  - FR_foot_1

left_hind:
  - BL_hip_2
  - BL_thigh_1
  - BL_calf_1
  - BL_foot_1

right_hind:
  - BR_hip_1
  - BR_thigh_1
  - BR_calf_1
  - BR_foot_4